# Site Settings

disqus:              #"your-disqus"

paginate:            1

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
